name: Generate Snake

on:
  schedule:
    # Runs at 12:00 AM UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: ${{ github.repository_owner }}/github-pages-snake
          publish_branch: gh-pages
          publish_dir: dist

