name: Generate GitHub Snake

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate contribution snake
      uses: Platane/snk@v2
      with:
        github_user: Mrudu17
        github_repo: Mrudu17
        svg_out_path: assets/github-contribution-grid-snake.svg  # Save to a public folder

    - name: Commit and push snake image
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add assets/github-contribution-grid-snake.svg
        git commit -m "Add contribution snake image"
        git push

